name: persistent-typed-db
version: 0.1.0.0
synopsis:    Type safe access to multiple database schemata.
description: See README.md for more details, examples, and fun.
category: Web
author: Matt Parsons
maintainer: parsonsmatt@gmail.com
copyright: 2017 Matt Parsons
license: BSD3
github: parsonsmatt/persistent-typed-db
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- aeson
- bytestring
- conduit             >= 1.3.0
- http-api-data
- monad-logger
- path-pieces
- persistent          >= 2.10.0
- persistent-template >= 2.7.0
- resource-pool
- resourcet           >= 1.2.0
- template-haskell
- text
- transformers

library:
  source-dirs: src
  ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wcompat -Wincomplete-uni-patterns

tests:
  specs:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - persistent-typed-db
    - hspec
    - persistent          >= 2.8.0
    - persistent-template
    - esqueleto
